<?php
/*
	TODO:
	- add fields to webform programatically


*/

function wf_beanstream_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == "webform_node_form") {
		$form['payment_options'] = array(
			'#type'			=> 'fieldset',
			'#title'		=> t('Payment Options'),
			'#summary'		=> 'adfsasd',
			'#collapsible'	=> true,
			'#collapsed'	=> true,
			'#group'		=> 'additional_settings',
		);

		$form['payment_options']['field_wfbs_use'] = $form['field_wfbs_use'];
		unset($form['field_wfbs_use']);
		$form['payment_options']['field_wfbs_api_key'] = $form['field_wfbs_api_key'];
		unset($form['field_wfbs_api_key']);
		$form['payment_options']['field_wfbs_price'] = $form['field_wfbs_price'];
		unset($form['field_wfbs_price']);
		$form['payment_options']['field_wfbs_flexible'] = $form['field_wfbs_flexible'];
		unset($form['field_wfbs_flexible']);
		$form['payment_options']['field_wfbs_reocurring'] = $form['field_wfbs_reocurring'];
		unset($form['field_wfbs_reocurring']);
		$form['payment_options']['field_wfbs_sku'] = $form['field_wfbs_sku'];
		unset($form['field_wfbs_sku']);
		$form['payment_options']['field_wfbs_note'] = $form['field_wfbs_note'];
		unset($form['field_wfbs_note']);
		$form['payment_options']['field_wfbs_prefix'] = $form['field_wfbs_prefix'];
		unset($form['field_wfbs_prefix']);

		$form['#validate'][] = '_wf_beanstream_form_alter_validate';
	}

	if (substr($form_id, 0, 19) == 'webform_client_form') {
		$node = $form['#node'];

		// check if payment processing is enabled
		if ($node && $node->field_wfbs_use && $node->field_wfbs_use['und'][0]['value'] == '1') {
			global $user;
			$user_fields = user_load($user->uid);

			if ($user_fields->uid != 0) {
				$first_name = $user_fields->field_first_name['und'][0]['value'];
				$last_name = $user_fields->field_last_name['und'][0]['value'];
				$email = $user_fields->mail;
			} else {
				$first_name = '';
				$last_name = '';
				$email = '';
			}

			$form['wfbs_personal_info'] = array(
				'#type'		=> 'fieldset',
				'#title'	=> t('Personal Information'),
				'#attributes' => array(
					'class' => array('gridContainer')
				),
			);
			$form['wfbs_payment_details'] = array(
				'#type'		=> 'fieldset',
				'#title'	=> t('Payment Details'),
				'#attributes' => array(
					'class' => array('gridContainer')
				),
			);

			$form['wfbs_personal_info']['wfbs_first_name'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('First Name'),
				'#required'	=> true,
				'#value'	=> $first_name,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);
			$form['wfbs_personal_info']['wfbs_last_name'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Last Name'),
				'#required'	=> true,
				'#value'	=> $last_name,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);
			$form['wfbs_personal_info']['wfbs_email'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Email Address'),
				'#value'	=> $email,
				'#required' => true,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);
			$form['wfbs_personal_info']['wfbs_phone'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Phone Number'),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);

			$form['wfbs_personal_info']['wfbs_address1'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Address 1'),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);
			$form['wfbs_personal_info']['wfbs_address2'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Address 2'),
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);
			$form['wfbs_personal_info']['wfbs_city'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('City'),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);
			$form['wfbs_personal_info']['wfbs_province'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Province'),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);
			$form['wfbs_personal_info']['wfbs_postal'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Postal Code'),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);
			$form['wfbs_personal_info']['wfbs_country'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Country'),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);

			// dynamic price
			if ($node->field_wfbs_flexible && $node->field_wfbs_flexible['und'][0]['value']) {
				$form['wfbs_payment_details']['wfbs_set_price'] = array(
					'#type'		=> 'radios',
					'#title'	=> t('Select Amount'),
					'#options'	=> array('25'=>'$25', '50'=>'$50', '100'=>'$100', '500'=>'$500', 'other'=>'Other'),
					'#prefix'	=> '<div class="col-1-2">',
					'#suffix'	=> '</div>',
				);

				$form['wfbs_payment_details']['wfbs_price'] = array(
					'#type'		=> 'textfield',
					'#title'	=> t('Other Amount'),
					'#element_validate' => array('element_validate_number'),
					'#prefix'	=> '<div class="col-1-2">',
					'#suffix'	=> '</div>',
				);
			}

			// reoccuring
			//field_wfbs_reocurring
			if ($node->field_wfbs_reocurring && $node->field_wfbs_reocurring['und'][0]['value']) {
				$form['wfbs_payment_details']['wfbs_reoccuring'] = array(
					'#type'		=> 'radios',
					'#title'	=> t('Donation Type'),
					'#default_value' => 0,
					'#options'	=> array(
						'0' => 'One Time',
						'1' => 'Monthly',
					),
					'#prefix'	=> '<div class="col-1-3">',
					'#suffix'	=> '</div>',
				);
			}

			// card info
			$form['wfbs_payment_details']['wfbs_cardholder_name'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Cardholder Name'),
				'#required'	=> true,
				'#value'	=> "$first_name $last_name",
				'#prefix'	=> '<div class="clear col-1-2">',
				'#suffix'	=> '</div><div class="col-1-2">&nbsp;</div>',
			);

			$form['wfbs_payment_details']['wfbs_card_number'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Credit Card Number'),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-2 clear">',
				'#suffix'	=> '</div>',
			);

			$form['wfbs_payment_details']['wfbs_card_type'] = array(
				'#type'		=> 'select',
				'#title'	=> t('Card Type'),
				'#options'	=> array(
					'mc'	=> t('Master Card'),
					'visa'	=> t('Visa'),
					'amex'	=> t('American Express'),
				),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-2">',
				'#suffix'	=> '</div>',
			);

			$form['wfbs_payment_details']['wfbs_card_month'] = array(
				'#type'		=> 'select',
				'#title'	=> t('Month'),
				'#options'	=> array(),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-6 clear">',
				'#suffix'	=> '</div>',
			);
			for ($i = 1; $i < 13; $i++) {
				$form['wfbs_payment_details']['wfbs_card_month']['#options'][sprintf('%02d', $i)] = $i;
			}

			$form['wfbs_payment_details']['wfbs_card_year'] = array(
				'#type'		=> 'select',
				'#title'	=> t('Year'),
				'#options'	=> array(),
				'#required'	=> true,
				'#prefix'	=> '<div class="col-1-6">',
				'#suffix'	=> '</div>',
			);
			for ($i = date('y'); $i < date('y') + 5; $i++) {
				$form['wfbs_payment_details']['wfbs_card_year']['#options'][$i] = $i;
			}

			$form['#validate'][] = '_wf_beanstream_payment_form_validate';
			$form['#submit'][] = '_wf_beanstream_payment_form_submit';
			$form['actions']['submit']['#value'] = t('Submit Donation');
		}
	}
}

function _wf_beanstream_form_alter_validate(&$form, &$form_state) {
	$form['field_wfbs_use'] = $form['payment_options']['field_wfbs_use'];
	unset($form['payment_options']['field_wfbs_use']);
	$form['field_wfbs_api_key'] = $form['payment_options']['field_wfbs_api_key'];
	unset($form['payment_options']['field_wfbs_api_key']);
	$form['field_wfbs_price'] = $form['payment_options']['field_wfbs_price'];
	unset($form['payment_options']['field_wfbs_price']);
	$form['field_wfbs_flexible'] = $form['payment_options']['field_wfbs_flexible'];
	unset($form['payment_options']['field_wfbs_flexible']);
	$form['field_wfbs_reocurring'] = $form['payment_options']['field_wfbs_reocurring'];
	unset($form['payment_options']['field_wfbs_reocurring']);
	$form['field_wfbs_sku'] = $form['payment_options']['field_wfbs_sku'];
	unset($form['payment_options']['field_wfbs_sku']);
	$form['field_wfbs_note'] = $form['payment_options']['field_wfbs_note'];
	unset($form['payment_options']['field_wfbs_note']);
	$form['field_wfbs_prefix'] = $form['payment_options']['field_wfbs_prefix'];
	unset($form['payment_options']['field_wfbs_prefix']);
}


function _wf_beanstream_payment_form_validate($form, &$form_state) {

	// bail early
	if (form_get_errors()) return;

	// check for valid node
	$node = $form['#node'];
	if (!$node) return;

	// if there are no other validation errors, do the transaction
	$key = isset($node->field_wfbs_api_key['und'])? $node->field_wfbs_api_key['und'][0]['value'] : '';
	$sku = isset($node->field_wfbs_sku['und'])? $node->field_wfbs_sku['und'][0]['value'] : '';
	$note = isset($node->field_wfbs_note['und'])? $node->field_wfbs_note['und'][0]['value'] : '';
	$prefix = isset($node->field_wfbs_prefix['und'])? $node->field_wfbs_prefix['und'][0]['value'] : '';

	if ($node->field_wfbs_flexible && $node->field_wfbs_flexible['und'][0]['value']) {
		if ($form_state['values']['wfbs_price']) {
			$price = $form_state['values']['wfbs_price'];
		} else if ($form_state['values']['wfbs_set_price']) {
			$price = $form_state['values']['wfbs_set_price'];
		} else {
			form_set_error('sdf', t('Please select an amount to donate'));
			return; // bail out
		}
	} else {
		$price = isset($node->field_wfbs_price['und'])? $node->field_wfbs_price['und'][0]['value'] : 0;
	}

	$firstname = $form_state['values']['wfbs_first_name'];
	$lastname = $form_state['values']['wfbs_last_name'];
	$email = $form_state['values']['wfbs_email'];
	$phone = $form_state['values']['wfbs_phone'];

	$cardholder_name = $form_state['values']['wfbs_cardholder_name'];
	$card_number = $form_state['values']['wfbs_card_number'];
	$card_type = $form_state['values']['wfbs_card_type'];
	$card_month = $form_state['values']['wfbs_card_month'];
	$card_year = $form_state['values']['wfbs_card_year'];

	$address1 = $form_state['values']['wfbs_address1'];
	$address2 = $form_state['values']['wfbs_address2'];
	$city = $form_state['values']['wfbs_city'];
	$province = $form_state['values']['wfbs_province'];
	$postal = $form_state['values']['wfbs_postal'];
	$country = $form_state['values']['wfbs_country'];


	$trn = new wf_beanstream_transaction($key); // TODO: Set key
	$trn->setCardInfo($cardholder_name, $card_number, $card_month, $card_year);
	$trn->setContactInfo($cardholder_name, $email, $phone, $address1, $address2, $city,
		$province, $postal, $country);
	$trn->setPersonalInfo($firstname, $lastname);

	$trn->addItem($sku, 1, $price, $note);

	if ($node->field_wfbs_reocurring && $node->field_wfbs_reocurring['und'][0]['value']) {
		$trn->makeMonthly($sku, $price);
	}

	// TODO add monthly option
	$trn->attemptTransaction($prefix);

	if ($trn->succeeded) {
		module_invoke_all('wfbs_payment_success', $trn, $form, $form_state);
	} else {
		form_set_error('', $trn->output['messageText']);
		module_invoke_all('wfbs_payment_failed', $trn, $form, $form_state);
	}
}

function _wf_beanstream_payment_form_submit($form, &$form_state) {


}

function wf_beanstream_wfbs_payment_success($trn, $form, $data) {
	global $user;
	$v = $data['values'];

	$transaction = new stdClass();
	$transaction->title = $trn->input['trnOrderNumber'];
	$transaction->type = 'transaction';
	node_object_prepare($transaction);

	$transaction->language = LANGUAGE_NONE;
	$transaction->uid = $user->uid;
	$transaction->status = 1;
	$transaction->promote = 0;
	$transaction->comment = 1;

	$transaction->field_first_name = array('und' => array(array('value' => $v['wfbs_first_name'])));
	$transaction->field_last_name = array('und' => array(array('value' => $v['wfbs_last_name'])));
	$transaction->field_contact_phone = array('und' => array(array('value' => $v['wfbs_phone'])));
	$transaction->field_contact_email = array('und' => array(array('value' => $v['wfbs_email'])));
	$transaction->field_contact_address1 = array('und' => array(array('value' => $v['wfbs_address1'])));
	$transaction->field_contact_address2 = array('und' => array(array('value' => $v['wfbs_address2'])));
	$transaction->field_contact_city = array('und' => array(array('value' => $v['wfbs_city'])));
	$transaction->field_contact_country = array('und' => array(array('value' => $v['wfbs_country'])));
	$transaction->field_contact_province = array('und' => array(array('value' => $v['wfbs_province'])));
	$transaction->field_postal = array('und' => array(array('value' => $v['wfbs_postal'])));
	$transaction->field_wfbs_price = array('und' => array(array('value' => $trn->totalAmount)));
	$transaction->field_wfbs_transaction = array('und' => array(array('value' => json_encode($trn->output))));

	$transaction = node_submit($transaction);
	node_save($transaction);
}

function wf_beanstream_wfbs_payment_failed($transaction, $form, $data) {

}