<?php

function r2ep_data_menu() {
	$items = array();
	$items['event_export'] = array(
		'title' => 'CSV Data Export',
		'access callback' => '_r2ep_data_event_access',
		'page callback' => '_r2ep_data_event'
	);

	return $items;
}

// only event owners and admins may access page
function _r2ep_data_event_access() {
	$event_id = arg(1);

	if (!$event_id || !is_numeric($event_id)) {
		return false;
	}

	$event = node_load($event_id);
	return node_access('update', $event);
}

function _r2ep_data_event($event_id) {
	if (!$event_id || !is_numeric($event_id)) {
		return;
	}

	$event = node_load($event_id);

	header('Cache-Control: public');
	header('Content-Type: application/octet-stream');
	header('Cache-Control: no-store, no-cache, must-revalidate');
	header('Cache-Control: post-check=0, pre-check=0');
	header("Content-Disposition: attachment; filename=\"{$event->title}.csv\";");
	header('Content-Transfer-encoding: binary');

	$query = <<<QUERY
SELECT
fname.field_first_name_value,
lname.field_last_name_value,
cell.field_cell_number_value,
gender.field_gender_value,
u.mail,
shirt.data as "Shirt",
g.field_goal_value,
c.field_donation_count_value,
t.field_total_donations_value,
(
	SELECT group_concat(team.title) FROM node AS team

	left join field_data_field_event as te on te.entity_id = team.nid
	left join field_data_field_runners as rs on rs.entity_id = team.nid

	WHERE
	team.type = 'team' AND
	te.field_event_target_id = :eid and
	rs.field_runners_target_id = n.uid
) as "Teams"
FROM node as n

left join field_data_field_event as e on e.entity_id = n.nid
left join users as u on u.uid = n.uid
left join field_data_field_first_name as fname on fname.entity_id = u.uid
left join field_data_field_last_name as lname on lname.entity_id = u.uid
left join field_data_field_cell_number as cell on cell.entity_id = u.uid
left join field_data_field_gender as gender on gender.entity_id = u.uid
left join field_data_field_goal as g on g.entity_id = n.nid
left join field_data_field_donation_count as c on c.entity_id = n.nid
left join field_data_field_total_donations as t on t.entity_id = n.nid
left join webform_submissions as wf on wf.uid = n.uid
left join webform_submitted_data as shirt on shirt.sid = wf.sid

where
n.type = 'campaign' and
e.field_event_target_id = :eid and
(fname.bundle = 'user' or fname.bundle IS NULL) and
(lname.bundle = 'user' or lname.bundle IS NULL) and
(cell.bundle = 'user' or cell.bundle IS NULL) and
(gender.bundle = 'user' or gender.bundle IS NULL) and
(shirt.cid = 6 or shirt.cid IS NULL)

group by n.nid
QUERY;
	$results = db_query($query, array(':eid' => $event_id));

	echo "firstname, lastname, cell, email, goal, count, total, teams\r\n";
	foreach($results as $result) {
		$values = array(
			$result->field_first_name_value,
			$result->field_last_name_value,
			$result->field_cell_number_value,
			$result->field_gender_value,
			$result->mail,
			$result->Shirt,
			$result->field_goal_value,
			$result->field_donation_count_value,
			$result->field_total_donations_value,
			('"'. $result->Teams .'"'),
		);
		echo implode(', ', $values) ."\r\n";
	}

	drupal_exit();
}

function r2ep_data_block_info() {
	$blocks = array();
	$blocks['r2ep_data_export'] = array(
		'info' => t('CSV Data Export')
	);

	return $blocks;
}

function r2ep_data_block_view($delta) {
	$block = array();

	switch($delta) {
		case 'r2ep_data_export':
			$node = menu_get_object();

			if ($node && $node->type == 'event') {
				$block['subject'] = '<none>';
				$block['content'] = "<a class=\"btn btn--block\" href=\"/event_export/{$node->nid}\">Download CSV</a>";
			}
			break;
	}

	return $block;
}