<?php

define('R2EP_EVENT_REGISTRATION_BLOCK', 'r2ep_event_registration_block');
define('R2EP_EVENT_COUNTDOWN_BLOCK', 'r2ep_event_countdown_block');

function r2ep_block_info() {
	$blocks = array();
	$blocks[R2EP_EVENT_REGISTRATION_BLOCK] = array(
		'info' => t('Register For This Event'),
	);
	$blocks[R2EP_EVENT_COUNTDOWN_BLOCK] = array(
		'info' => t('Event countdown'),
	);

	return $blocks;
}

function r2ep_block_view($delta = '') {
	$block = array();

	switch ($delta) {
		case R2EP_EVENT_REGISTRATION_BLOCK:
			$block['subject'] = t('Register for this event');
			$block['content'] = _r2ep_event_registration_block();
			break;
		case R2EP_EVENT_COUNTDOWN_BLOCK:
			$block['subject'] = t('Event Countdown');
			$block['content'] = _r2ep_event_countdown();
			break;
	}

	return $block;
}

function _r2ep_event_registration_block() {
	global $user;
	$node = menu_get_object();

	if ($node->field_registration_form) {
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type', 'node')
			->entityCondition('bundle', 'campaign')
			->propertyCondition('uid', $user->uid)
			->propertyCondition('status', 1)
			->fieldCondition('field_event', 'target_id', $node->nid);

		$count = clone $query;
		$count = $count->count()->execute();

		if ($count) {
			$query->range(0, 1);
			$results = $query->execute();
			$node = reset($results['node']);
			$link = drupal_get_path_alias('node/'. $node->nid);
			$content = "<div style='padding-top: 10px;'><a href=\"/$link\">View My<br/><span class=\"large\">Campaign</span></a></div>";
		} else {
			$form = $node->field_registration_form['und'][0]['target_id'];
			$link = drupal_get_path_alias("node/$form") .'?eid='. $node->nid;
			$content = "<div><a href=\"/$link\"><span class=\"large\">Register</span><br/>For This Event</a></div>";
		}
	} else {
		$content = '';
	}

	return $content;
}

function _r2ep_event_countdown() {
	$node = menu_get_object();

	if ($node->field_date) {
		$date = $node->field_date['und'][0]['value'];
		$now = time();

		$diff = abs($now - $date);
		$days = floor($diff/(60*60*24));
		$hours = floor(($diff - $days*60*60*24)/ (60*60));
		$minutes = floor(($diff - $days*60*60*24 - $hours*60*60)/ (60));

		$content = array(
			'#theme'		=> 'item_list',
			'#items'	=> array(),
			'#attributes'	=> array(
				'class' => array('gridContainer eventCountdown'),
			),
		);

		$content['#items'][] = array(
			'data' => '<div class="darkBlock">'. $days .'</div>'. t('days'),
			'class' => array('col-1-3'),
		);
		$content['#items'][] = array(
			'data' => '<div class="darkBlock">'. $hours .'</div>'. t('hours'),
			'class' => array('col-1-3'),
		);
		$content['#items'][] = array(
			'data' => '<div class="darkBlock">'. $minutes .'</div>'. t('minutes'),
			'class' => array('col-1-3'),
		);

		return $content;
	}

}

// handle successful payments
// function r2ep_wfbs_payment_success($transaction, $form, $data) {
// }

// handle failed payments
// function r2ep_wfbs_payment_failed($transaction, $form, $data) {
// }

// handle form submissions

function r2ep_form_alter(&$form, &$form_state, $form_id) {

	if (isset($form['#node']) &&
		isset($form['#node']->field_r2ep_make_campaign) &&
		$form['#node']->field_r2ep_make_campaign['und'][0]['value']) {
		$form['#submit'][] = '_r2ep_campaign_submitted';
	}

	if (isset($form['#node']) &&
		isset($form['#node']->field_r2ep_make_donation) &&
		$form['#node']->field_r2ep_make_donation['und'][0]['value']) {
		$form['#submit'][] = '_r2ep_donation_submitted';
	}
}

// create a campaign after a users submits a registration form
function _r2ep_campaign_submitted(&$form, &$form_state) {
	global $user;
	$user_fields = user_load($user->uid);

	$campaign = new stdClass();
	$campaign->title = $user_fields->realname .'\'s '. t('Campaign');
	$campaign->type = 'campaign';
	node_object_prepare($campaign);

	$campaign->language = LANGUAGE_NONE;
	$campaign->uid = $user->uid;
	$campaign->status = 1;
	$campaign->promote = 0;
	$campaign->comment = 1; // off
	$campaign->field_event = array('und' => array(array(
		'target_id' => $form_state['values']['submitted'][4]
	))); // event_id

	$campaign = node_submit($campaign);
	node_save($campaign);

	drupal_goto('node/'. $campaign->nid .'/edit');
}

function _r2ep_webform_component_mapping($node) {
	$mapping = array();
	$components = $node->webform['components'];

	foreach ($components as $i => $component) {
		$key = $component['form_key'];
		$mapping[$key] = $i;
	}

	return $mapping;
}


// create a donation after a user submits a donation form
function _r2ep_donation_submitted(&$form, &$form_state) {
	$donation = new stdClass();
	$donation->title = 'donation-'. mktime();
	$donation->type = 'donation';
	node_object_prepare($donation);

	$donation->language = LANGUAGE_NONE;
	$donation->uid = 0;
	$donation->status = 1;
	$donation->promote = 0;
	$donation->comment = 1;

	$donation->field_first_name = array('und' => array(array('value' => $form_state['values']['wfbs_first_name'])));
	$donation->field_last_name = array('und' => array(array('value' => $form_state['values']['wfbs_last_name'])));
	$donation->field_contact_email = array('und' => array(array('value' => $form_state['values']['wfbs_email'])));
	$donation->field_contact_phone = array('und' => array(array('value' => $form_state['values']['wfbs_phone'])));
	$donation->field_contact_address1 = array('und' => array(array('value' => $form_state['values']['wfbs_address1'])));
	$donation->field_contact_address2 = array('und' => array(array('value' => $form_state['values']['wfbs_address2'])));
	$donation->field_contact_city = array('und' => array(array('value' => $form_state['values']['wfbs_city'])));
	$donation->field_contact_province = array('und' => array(array('value' => $form_state['values']['wfbs_province'])));
	$donation->field_contact_postal = array('und' => array(array('value' => $form_state['values']['wfbs_postal'])));
	$donation->field_contact_country = array('und' => array(array('value' => $form_state['values']['wfbs_country'])));
	$donation->field_campaign = array('und' => array(array('target_id' => $form_state['values']['submitted'][4])));

	if ($form_state['values']['wfbs_price']) {
		$donation->field_wfbs_price = array('und' => array(array('value' => $form_state['values']['wfbs_price'])));
	} else {
		$donation->field_wfbs_price = array('und' => array(array('value' => $form_state['values']['wfbs_set_price'])));
	}

	$donation = node_submit($donation);
	node_save($donation);
}